"""edit Item table

Revision ID: e07f163857e7
Revises: 8f5da1f43f42
Create Date: 2023-04-14 22:20:29.999088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07f163857e7'
down_revision = '8f5da1f43f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('model', sa.String(length=50), nullable=False)
        )
        batch_op.alter_column(
            'brand',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=20),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column(
            'brand',
            existing_type=sa.String(length=20),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )
        batch_op.drop_column('model')

    # ### end Alembic commands ###
